config/routes.rb
Rails.application.routes.draw do
  resources :tweets
  root "tweets#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  validates :message, presence: true, length: { maximum: 140 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: %i[show edit update destroy]

  def index
    @tweets = Tweet.all.order(created_at: :desc)
  end

  def show; end

  def new
    @tweet = Tweet.new
  end

  def create
    @tweet = Tweet.new(tweet_params)
    @tweet.tdate = Time.current

    if @tweet.save
      flash[:notice] = "ツイートを作成しました"
      redirect_to @tweet
    else
      flash.now[:alert] = "メッセージは1文字以上、140文字以下にしてください"
      render :new
    end
  end

  def edit; end

  def update
    if @tweet.update(tweet_params)
      flash[:notice] = "ツイートを更新しました"
      redirect_to @tweet
    else
      flash.now[:alert] = "メッセージは1文字以上、140文字以下にしてください"
      render :edit
    end
  end

  def destroy
    @tweet = Tweet.find(params[:id])
    if @tweet.destroy
      flash[:notice] = "ツイートが削除されました"
      redirect_to tweets_path
    else
      flash[:alert] = "ツイートの削除に失敗しました"
      redirect_to tweet_path(@tweet)
    end
  rescue => e
    logger.error "Error deleting tweet: #{e.message}"
    flash[:alert] = "エラーが発生しました: #{e.message}"
    redirect_to tweets_path
  end


  def set_tweet
    @tweet = Tweet.find(params[:id])
  end

  def tweet_params
    params.require(:tweet).permit(:message)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Twitter</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if flash[:notice] %>
      <p style="color: green;"><%= flash[:notice] %></p>
    <% elsif flash[:alert] %>
      <p style="color: red;"><%= flash[:alert] %></p>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/tweets/edit.html.erb
<h1>ツイートを編集</h1>

<%= form_with(model: @tweet, local: true) do |form| %>
  <% if @tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tweet.errors.count, "error") %> prevented this tweet from being saved:</h2>
      <ul>
        <% @tweet.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :message %><br>
    <%= form.text_area :message, size: "60x5" %>
  </div>

  <div class="actions">
    <%= form.submit "更新する" %>
  </div>
<% end %>

<%= link_to '戻る', tweet_path(@tweet) %>

app/views/tweets/index.html.erb
<h1>ツイート一覧</h1>

<%= link_to '新しいツイート', new_tweet_path %>

<ul>
  <% @tweets.each do |tweet| %>
    <li>
      <%= link_to tweet.message, tweet_path(tweet) %>
      <small><%= distance_of_time_in_words_to_now(tweet.tdate) %>前</small>
      <%= link_to '編集', edit_tweet_path(tweet) %>
      <%= form_with url: tweet_path(tweet), method: :delete, local: true do %>
        <%= submit_tag '削除', data: { confirm: '本当に削除しますか？' } %>
      <% end %>
    </li>
  <% end %>
</ul>

app/views/tweets/new.html.erb
<h1>新しいツイート</h1>

<%= form_with(model: @tweet, local: true) do |form| %>
  <% if @tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tweet.errors.count, "error") %> prevented this tweet from being saved:</h2>
      <ul>
        <% @tweet.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :message %><br>
    <%= form.text_area :message, size: "60x5" %>
  </div>

  <div class="actions">
    <%= form.submit "ツイートする" %>
  </div>
<% end %>

<%= link_to '戻る', tweets_path %>

app/views/tweets/show.html.erb
<h1>ツイート詳細</h1>

<p>
  <strong>メッセージ:</strong>
  <%= @tweet.message %>
</p>

<p>
  <strong>ツイート日時:</strong>
  <%= time_ago_in_words(@tweet.tdate) %>前
</p>

<%= link_to '編集', edit_tweet_path(@tweet) %> |
<%= form_with url: tweet_path(@tweet), method: :delete, local: true do %>
  <%= submit_tag '削除', data: { confirm: '本当に削除しますか？' } %>
<% end %>

<%= link_to '戻る', tweets_path %>